// Code generated by wit-bindgen-go. DO NOT EDIT.

package processor

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// S3SinkShape is used for storage in variant or result types.
type S3SinkShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(S3Sink{})]byte
}
