// Code generated by wit-bindgen-go. DO NOT EDIT.

package processor

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "tangent:logs/processor@0.1.0".
var Exports struct {
	// ProcessLogs represents the caller-defined, exported function "process-logs".
	//
	//	process-logs: func(logs: list<u8>) -> result<list<output>, string>
	ProcessLogs func(logs cm.List[uint8]) (result cm.Result[cm.List[Output], cm.List[Output], string])
}
