// Code generated by wit-bindgen-go. DO NOT EDIT.

package processor

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "tangent:logs@0.1.0".

//go:wasmexport process-logs
//export process-logs
func wasmexport_ProcessLogs(logs0 *uint8, logs1 uint32) (result *cm.Result[cm.List[Output], cm.List[Output], string]) {
	logs := cm.LiftList[cm.List[uint8]]((*uint8)(logs0), (uint32)(logs1))
	result_ := Exports.ProcessLogs(logs)
	result = &result_
	return
}
