module_type: go
entry_point: .
batch_size: 1024
sources:
  socket_main:
    type: socket
    path: "/tmp/sidecar.sock"
sinks:
  s3_bucket:
    type: s3
    bucket_name: my-bucket
    max_inflight: 4
    max_file_age_seconds: 15