runtime:
    batch_size: 1024
    plugins_path: plugins/
plugins:
  zeek:
    module_type: go
    path: .
    tests:
      - input: tests/conn.json
        expected:  tests/conn_out.json
sources:
  network_input:
    type: tcp
    bind_address: 0.0.0.0:9000
sinks:
  blackhole:
    type: blackhole

dag:
  - from:
      kind: source
      name: network_input
    to:
      - kind: plugin
        name: zeek

  - from:
      kind: plugin
      name: zeek
    to:
      - kind: sink
        name: blackhole