// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package main
import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA84b1c3cDecodeEnrichmentEasyjsonLocal(in *jlexer.Lexer, out *EnrichedOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ip_address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IPAddress = string(in.String())
			}
		case "country":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Country = string(in.String())
			}
		case "service":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Service = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA84b1c3cEncodeEnrichmentEasyjsonLocal(out *jwriter.Writer, in EnrichedOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ip_address\":"
		out.RawString(prefix[1:])
		out.String(string(in.IPAddress))
	}
	{
		const prefix string = ",\"country\":"
		out.RawString(prefix)
		out.String(string(in.Country))
	}
	{
		const prefix string = ",\"service\":"
		out.RawString(prefix)
		out.String(string(in.Service))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EnrichedOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA84b1c3cEncodeEnrichmentEasyjsonLocal(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EnrichedOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA84b1c3cEncodeEnrichmentEasyjsonLocal(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EnrichedOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA84b1c3cDecodeEnrichmentEasyjsonLocal(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EnrichedOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA84b1c3cDecodeEnrichmentEasyjsonLocal(l, v)
}
