// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package main
import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA84b1c3cDecodeGithubwebhooksEasyjsonLocal(in *jlexer.Lexer, out *Alert) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "triggered":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Triggered = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA84b1c3cEncodeGithubwebhooksEasyjsonLocal(out *jwriter.Writer, in Alert) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"triggered\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Triggered))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Alert) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA84b1c3cEncodeGithubwebhooksEasyjsonLocal(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Alert) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA84b1c3cEncodeGithubwebhooksEasyjsonLocal(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Alert) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA84b1c3cDecodeGithubwebhooksEasyjsonLocal(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Alert) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA84b1c3cDecodeGithubwebhooksEasyjsonLocal(l, v)
}
