runtime:
    batch_size: 1024
    plugins_path: "../../plugins/"
plugins:
  zeek:
    module_type: go
    path: ../../examples/zeek/
    tests:
      - input: ../../examples/zeek/tests/conn.json
        expected:  ../../examples/zeek/tests/conn_out.json
  python:
    module_type: py
    path: ../../examples/python/mapper.py
sources:
  socket_main:
    type: socket
    path: "/tmp/sidecar.sock"
sinks:
  blackhole:
    type: blackhole

dag:
  - from:
      kind: source
      name: socket_main
    to:
      - kind: plugin
        name: zeek

  - from:
      kind: plugin
      name: zeek
    to:
      - kind: sink
        name: blackhole