// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package main
import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE9e01bf6DecodeGolangEasyjsonTypes(in *jlexer.Lexer, out *ExampleOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Msg = string(in.String())
			}
		case "level":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Level = string(in.String())
			}
		case "seen":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Seen = int64(in.Int64())
			}
		case "duration":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Duration = float64(in.Float64())
			}
		case "service":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Service = string(in.String())
			}
		case "tags":
			if in.IsNull() {
				in.Skip()
				out.Tags = nil
			} else {
				in.Delim('[')
				if out.Tags == nil {
					if !in.IsDelim(']') {
						out.Tags = make([]string, 0, 4)
					} else {
						out.Tags = []string{}
					}
				} else {
					out.Tags = (out.Tags)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.Tags = append(out.Tags, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE9e01bf6EncodeGolangEasyjsonTypes(out *jwriter.Writer, in ExampleOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix[1:])
		out.String(string(in.Msg))
	}
	{
		const prefix string = ",\"level\":"
		out.RawString(prefix)
		out.String(string(in.Level))
	}
	{
		const prefix string = ",\"seen\":"
		out.RawString(prefix)
		out.Int64(int64(in.Seen))
	}
	{
		const prefix string = ",\"duration\":"
		out.RawString(prefix)
		out.Float64(float64(in.Duration))
	}
	{
		const prefix string = ",\"service\":"
		out.RawString(prefix)
		out.String(string(in.Service))
	}
	{
		const prefix string = ",\"tags\":"
		out.RawString(prefix)
		if in.Tags == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Tags {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ExampleOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE9e01bf6EncodeGolangEasyjsonTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ExampleOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE9e01bf6EncodeGolangEasyjsonTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ExampleOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE9e01bf6DecodeGolangEasyjsonTypes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ExampleOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE9e01bf6DecodeGolangEasyjsonTypes(l, v)
}
