// Code generated by tangentgen; DO NOT EDIT.

package main

import (
	pluginout "github.com/telophasehq/tangent-sdk-go"
)

// AppendToArena appends ExampleOutput into the arena as an object and returns the root node index.
func (x ExampleOutput) AppendToArena(ab *pluginout.ArenaBuilder, st *pluginout.StringTable) uint32 {
	ab.ObjectStartReserve(6)

	Msg_str_idx := ab.String(x.Msg)
	ab.ObjectAddFieldKey("message", Msg_str_idx)
	Level_str_idx := ab.String(x.Level)
	ab.ObjectAddFieldKey("level", Level_str_idx)
	Seen_int_idx := ab.Int(int64(x.Seen))
	ab.ObjectAddFieldKey("seen", Seen_int_idx)
	Duration_float_idx := ab.Float(float64(x.Duration))
	ab.ObjectAddFieldKey("duration", Duration_float_idx)
	Service_str_idx := ab.String(x.Service)
	ab.ObjectAddFieldKey("service", Service_str_idx)
	ab.ArrayStartReserve(len(x.Tags))
	for i := range x.Tags {
		ab.ArrayAdd(ab.String(x.Tags[i]))
	}
	Tags_slice_idx := ab.ArrayEnd()
	ab.ObjectAddFieldKey("tags", Tags_slice_idx)

	return ab.ObjectEnd()
}
