name: Scaffold services and run tests

on:
  pull_request:

jobs:
  scaffold-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tangent CLI
        run: cargo install --path crates/cli

      - name: Scaffold Go plugin
        run: tangent plugin scaffold --name go-plugin --lang go

      - name: Scaffold Python plugin
        run: tangent plugin scaffold --name py-plugin --lang python

      - name: Run make test (Go)
        run: make test
        working-directory: go-plugin

      - name: Run make test (Python)
        run: make test
        working-directory: py-plugin
